apiVersion: v1
appVersion: "v2.25.5"
description: A Helm chart for Deploying Jumpserver on Kubernetes
engine: gotpl
home: https://jumpserver.org
icon: https://jumpserver.org/images/logo/favicon.ico
maintainers:
- email: support@fit2cloud.com
  name: jumpserver
sources:
- https://github.com/jumpserver/
name: jumpserver
version: 2.25.5
