annotations:
  category: "Application"
  licenses: "GPL-3.0"
apiVersion: v2
appVersion: "v4.6.0"
description: A Helm chart for Deploying Jumpserver on Kubernetes
home: https://jumpserver.org
icon: https://jumpserver.org/images/logo/favicon.ico
maintainers:
- name: FIT2CLOUD, Inc. All Rights Reserved.
  url: https://github.com/jumpserver/helm-charts
sources:
- https://github.com/jumpserver/helm-charts/tree/main/charts/jumpserver
name: jumpserver
version: v4.6.0
